project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

recipes/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'recipes'

urlpatterns = [
    path('', views.start, name='home'),
    path('recipes/<int:id>/', views.recipes, name='recipe'),
    path('recipes/category/<int:category_id>/', views.category, name='category'),
]

#servindo os arquivos de imagens para quando serem clicadas, abrirem uma url sem erro
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


recipes/models.py
from django.contrib.auth.models import User #importando usuário do próprio Django
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    #definindo método para mudar o nome correto dentro do setor ADMIN do Django
    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=65)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=50)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_publish = models.BooleanField()
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d')
    #quando a categoria for deletada, o campo da receita ficará como NUll
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None) #Criando um atributo para fazer a relação da classe Category com a de Recipes
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) #Criando um atributo para fazer a relação da classe Category com a de Recipes

    def __str__(self):
        return self.title
    

recipes/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from utils.recipes.factory import make_recipe
from recipes import models

# Create your views here.
def start(request):
    Recipes = models.Recipe.objects.filter(is_publish=True).order_by('-id')

    return render(request, 'recipes/pages/home.html', {
        'recipes' : Recipes,
    })

def recipes(request, id):

    Recipes = get_object_or_404(models.Recipe, id=id, is_publish=True,) 

    return render(request, 'recipes/pages/recipe-view.html', {
        'recipe' : Recipes,
        'is_datail_page' : True,
    })

def category(request, category_id):
    # Recipes = models.Recipe.objects.filter(category__id=category_id, is_publish=True).order_by('-id')#Filtrando a através do model Recipe a chave estrangeira através do __ para identificar o id do campo categoria

    Recipes = get_list_or_404(models.Recipe.objects.filter(category__id=category_id, is_publish=True).order_by('-id'))

    return render(request, 'recipes/pages/category.html',
            {
                'recipes' : Recipes,
              #  'title' : f'{Recipes.first().category.name} - Category'    #Seria utilizado se fosse passado uma Queryset
                'title' : f'{Recipes[0].category.name} - Caregory'     #Passando o valor Recipes[0], pois o Recipes é uma Lista
            } 
                  )

recipes/templates/recipes/pages/category.html
{% extends "global/base.html" %}

{% block title %} {{title}}{% endblock title %}

    {% block content %}]

            <div class="main-content main-content-list container">

                {% for recipe in recipes %}
                    {% include "recipes/partials/_recipes.html" %}
                {% endfor %}
            </div>
            
    {% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends "global/base.html" %}

{% block title %} Inicio {% endblock title %}

    {% block content %}]

            <div class="main-content main-content-list container">

                {% for recipe in recipes %}
                    {% include "recipes/partials/_recipes.html" %}
                {% empty %}
                    <div class="center">
                        <h1>No Recipes found here! 😥😭</h1>
                    </div>
                {% endfor %}
                
            </div>
            
    {% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends "global/base.html" %}
{% block title %} {{recipe.title}} {% endblock title %} 
   
    {% block content %}
            <div class="main-content main-content-detail container">
                {% include "recipes/partials/_recipes.html" %}
            </div>
    {% endblock content %}

recipes/templates/recipes/partials/_footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.otaviomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Raul Teles</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/_head.html
{% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href=" {% static "recipes/css/style.css" %}">
    

recipes/templates/recipes/partials/_header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href=" {% url "recipes:home" %}">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">
                    Recipes
                </span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/_recipes.html
<div class="recipe recipe-list-item">
    <a href=" {% url "recipes:recipe" recipe.id %}">
        <div class="recipe-cover">
            <img src="{{recipe.cover.url}}" alt="Imagem temporaria">
        </div>
    </a>
    <div class="recipe-title-container">
        <a href=" {% url "recipes:recipe" recipe.id %}">
        <h2 class="recipe-title">
            {{recipe.title}}
        </h2>
        </a>
    </div>
 
    <div class="recipe-author">
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author is not None %}
                    {% if recipe.author.first_name %}
                        {{recipe.author.first_name}} {{recipe.author.last_name}}
                    {% else %}
                        {{recipe.author.username}}
                    {% endif %}
                {% else %}
                Desconhecido
                {% endif %}

            </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}} às {{recipe.created_at|date:"H:i"}}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url "recipes:category" recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_datail_page is not True %}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url "recipes:recipe" recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_datail_page is True %}
        <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is True %}
            {{recipe.preparation_steps |safe}}
        {% else %}
            {{recipe.preparation_steps |linebreaksbr}}
        {% endif %}
        </div>

    {% endif %}
</div>

recipes/templates/recipes/partials/_search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>